Repository pulp/pulp_ansible, pull requests merged in 2024-02, with the labels that each got.

#1765 Add AnsibleNamespaceMetadata to modelresources
  CHANGES/1764.bugfix
  pulp_ansible/app/modelresource.py
  pulp_ansible/tests/functional/api/test_export_import.py
Labels: backport-0.18, backport-0.21, backport-0.20

#1769 Fix namespace sync with missing avatar_sha256
  CHANGES/1772.bugfix
  functest_requirements.txt
  pulp_ansible/app/models.py
  pulp_ansible/app/serializers.py
  pulp_ansible/app/tasks/collections.py
Labels: backport-0.21, backport-0.20

#1777 Patchback/backports/0.21/3a5e9610b025587a021f84c178ad03ddd342e49b/pr 1769
  CHANGES/1772.bugfix
  pulp_ansible/app/models.py
  pulp_ansible/app/serializers.py
  pulp_ansible/app/tasks/collections.py
Labels: backport-0.20
