Repository pulp/pulp_ansible, pull requests merged in 2024-10, with the labels that each got.

#1989 Fix some 500 errors in the galaxy api
  CHANGES/galaxy500s.bugfix
  pulp_ansible/app/galaxy/v3/views.py
  pulp_ansible/app/settings.py
Labels: no-issue, no-changelog

#1992 Remove CollectionVersion is_highest
  CHANGES/+is_highest.removal
  CHANGES/1986.bugfix
  CHANGES/1986.removal
  pulp_ansible/app/modelresource.py
  pulp_ansible/app/models.py
  pulp_ansible/app/tasks/collections.py
  pulp_ansible/app/tasks/upload.py
  pulp_ansible/app/viewsets.py
  pulp_ansible/tests/functional/api/collection/v3/test_redirects.py
  pulp_ansible/tests/unit/test_tasks.py
Labels: no-changelog

#2001 Use the collectionversion timestamps to reflect a collection's updated_at
  CHANGES/2000.bugfix
  pulp_ansible/app/galaxy/v3/views.py
  pulp_ansible/tests/functional/api/collection/v3/test_serializers.py
Labels: backport-0.21, backport-0.20, backport-0.22

#1995 Fix Any serializer type regression breaking Ruby bindings
  CHANGES/+fix-any-type.bugfix
  pulp_ansible/app/fields.py
  pulp_ansible/app/galaxy/v3/serializers.py
  pulp_ansible/app/serializers.py
Labels: backport-0.15, backport-0.16, backport-0.18, backport-0.21, backport-0.20, backport-0.22, no-issue

#2003 [SAT-29057] Fix constraints violation on is_highest in import
  CHANGES/1986.bugfix
  pulp_ansible/app/modelresource.py
Labels: backport-0.21, backport-0.20, no-issue

#1997 Remove test dependency orion-util
  functest_requirements.txt
  pulp_ansible/pytest_plugin.py
  pulp_ansible/tests/functional/api/collection/test_crud_collection_versions.py
  pulp_ansible/tests/functional/api/collection/test_sync.py
  pulp_ansible/tests/functional/api/collection/v3/test_collection.py
  pulp_ansible/tests/functional/api/collection/v3/test_collection_naming_edgecases.py
  pulp_ansible/tests/functional/api/collection/v3/test_collection_version_search.py
  pulp_ansible/tests/functional/api/collection/v3/test_content_guard.py
  pulp_ansible/tests/functional/api/collection/v3/test_deletion.py
  pulp_ansible/tests/functional/api/test_export_import.py
  pulp_ansible/tests/functional/constants.py
  pulp_ansible/tests/functional/utils.py
  pulp_ansible/tests/unit/test_cv_index.py
  pulp_ansible/tests/unit/utils.py
  unittest_requirements.txt
Labels: no-issue, no-changelog

#2008 [PR #1995/2d90c0c5 backport][0.16] Fix Any serializer type regression breaking Ruby bindings
  CHANGES/+fix-any-type.bugfix
  pulp_ansible/app/fields.py
  pulp_ansible/app/galaxy/v3/serializers.py
  pulp_ansible/app/serializers.py
Labels: no-issue

#2009 [PR #1995/2d90c0c5 backport][0.18] Fix Any serializer type regression breaking Ruby bindings
  CHANGES/+fix-any-type.bugfix
  pulp_ansible/app/fields.py
  pulp_ansible/app/galaxy/v3/serializers.py
  pulp_ansible/app/serializers.py
Labels: no-issue
