Repository pulp/pulp_ansible, pull requests merged in 2024-05, with the labels that each got.

#1831 Add ansible api hostname to api cache key.
  CHANGES/1833.bugfix
  pulp_ansible/app/galaxy/v3/views.py
Labels: backport-0.21

#1837 Fix import collection marks and signatures
  CHANGES/1836.bugfix
  pulp_ansible/app/modelresource.py
Labels: backport-0.15, backport-0.16, backport-0.20

#1869 Fix sync on failed namespace avatar downloads
  CHANGES/1868.bugfix
  pulp_ansible/app/tasks/collections.py
Labels: backport-0.21, backport-0.20
