Repository pulp/pulp_ansible, pull requests merged in 2025-04, with the labels that each got.

#2157 Work around an issue with drf 3.16
  CHANGES/+search_list_serializer.bugfix
  pulp_ansible/app/galaxy/v3/serializers.py
  pyproject.toml
Labels: no-issue

#2166 Fix log for avatar downloads
  CHANGES/+log_namespace.bugfix
  pulp_ansible/app/tasks/collections.py
Labels: no-issue

#2168 Added namespace progress report
  CHANGES/+namespace_progress_report.feature
  CHANGES/2138.bugfix
  pulp_ansible/app/tasks/collections.py
  pulp_ansible/tests/functional/api/collection/test_sync.py
Labels: backport-0.21, backport-0.20, backport-0.24

#2182 dded namespace progress report
  CHANGES/+namespace_progress_report.feature
  CHANGES/2138.bugfix
  pulp_ansible/app/tasks/collections.py
  pulp_ansible/tests/functional/api/collection/test_sync.py
Labels: backport-0.21, backport-0.20, backport-0.22
